language: php
php:
    - 7.1
    - hhvm

env: dependencies="--prefer-stable"

matrix:
    allow_failures:
        - php: hhvm

    include:
        - php: 7.2
          env: dependencies="--prefer-lowest"

script:
    - vendor/bin/tester tests -s -p php -c tests/php-unix.ini
    - php temp/code-checker/src/code-checker.php

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester & Code Checker
    - composer self-update
    - travis_retry composer update --no-interaction --prefer-dist $dependencies
    - travis_retry composer create-project nette/code-checker temp/code-checker ~2.5 --no-interaction

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    on_success: never
